version: '3.3'
services:
  nginx:
    container_name: reverse_proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/certs:/etc/nginx/certs

  app1:
    container_name: app1
    image: httpd:2.4.48
    restart: always
    environment:
      VIRTUAL_HOST: cdi.normanmbouende.com
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins
    environment:
      VIRTUAL_HOST: normanmbouende.com
      VIRTUAL_PORT: 8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
